"""initial schema: bet, position, suggestion, market, game, chat_message

Revision ID: 4fab9c57deec
Revises: 
Create Date: 2026-05-25 18:48:34.341604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fab9c57deec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('referenced_ids', sa.JSON(), nullable=True),
    sa.Column('agent_initiated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sport IN ('soccer', 'nfl')", name='ck_chat_sport'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=8), nullable=True),
    sa.Column('live_state', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sport IN ('soccer', 'nfl')", name='ck_game_sport'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_game_external_id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index('ix_game_sport_status_kickoff', ['sport', 'status', 'kickoff'], unique=False)

    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('kalshi_ticker', sa.String(length=64), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('yes_price_cents', sa.Integer(), nullable=True),
    sa.Column('no_price_cents', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settlement', sa.String(length=8), nullable=True),
    sa.Column('settlement_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sport IN ('soccer', 'nfl')", name='ck_market_sport'),
    sa.CheckConstraint('no_price_cents IS NULL OR (no_price_cents >= 1 AND no_price_cents <= 99)', name='ck_market_no_price_range'),
    sa.CheckConstraint('yes_price_cents IS NULL OR (yes_price_cents >= 1 AND yes_price_cents <= 99)', name='ck_market_yes_price_range'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kalshi_ticker', name='uq_market_kalshi_ticker')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('kalshi_ticker', sa.String(length=64), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_entry_price_cents', sa.Integer(), nullable=False),
    sa.Column('current_price_cents', sa.Integer(), nullable=True),
    sa.Column('unrealized_pnl_cents', sa.Integer(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sport IN ('soccer', 'nfl')", name='ck_position_sport'),
    sa.CheckConstraint('avg_entry_price_cents >= 1 AND avg_entry_price_cents <= 99', name='ck_position_avg_entry_range'),
    sa.CheckConstraint('quantity >= 0', name='ck_position_quantity_nonneg'),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'side', name='uq_position_market_side')
    )
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_group_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('suggested_price_cents', sa.Integer(), nullable=False),
    sa.Column('suggested_size_cents', sa.Integer(), nullable=False),
    sa.Column('kelly_fraction_bps', sa.Integer(), nullable=True),
    sa.Column('estimated_edge_bps', sa.Integer(), nullable=True),
    sa.Column('ai_probability_pct', sa.Integer(), nullable=True),
    sa.Column('market_probability_pct', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('urgency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('acted_on_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("sport IN ('soccer', 'nfl')", name='ck_suggestion_sport'),
    sa.CheckConstraint('suggested_price_cents >= 1 AND suggested_price_cents <= 99', name='ck_suggestion_price_range'),
    sa.CheckConstraint('suggested_size_cents >= 0', name='ck_suggestion_size_nonneg'),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.create_index('ix_suggestion_group', ['suggestion_group_id'], unique=False)
        batch_op.create_index('ix_suggestion_sport_status', ['sport', 'status'], unique=False)

    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('parent_bet_id', sa.Integer(), nullable=True),
    sa.Column('kalshi_order_id', sa.String(length=64), nullable=True),
    sa.Column('kalshi_fill_id', sa.String(length=64), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_price_cents', sa.Integer(), nullable=False),
    sa.Column('exit_price_cents', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stake_cents', sa.Integer(), nullable=False),
    sa.Column('pnl_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('exit_type', sa.String(length=24), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('kelly_fraction_bps', sa.Integer(), nullable=True),
    sa.Column('ai_probability_pct', sa.Integer(), nullable=True),
    sa.Column('human_override_sizing', sa.Boolean(), nullable=False),
    sa.Column('human_override_direction', sa.Boolean(), nullable=False),
    sa.Column('human_reasoning', sa.Text(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('timing', sa.String(length=16), nullable=False),
    sa.Column('game_period', sa.String(length=8), nullable=True),
    sa.Column('game_clock', sa.String(length=16), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sport IN ('soccer', 'nfl')", name='ck_bet_sport'),
    sa.CheckConstraint('entry_price_cents >= 1 AND entry_price_cents <= 99', name='ck_bet_entry_price_range'),
    sa.CheckConstraint('exit_price_cents IS NULL OR (exit_price_cents >= 1 AND exit_price_cents <= 99)', name='ck_bet_exit_price_range'),
    sa.CheckConstraint('quantity >= 1', name='ck_bet_quantity_positive'),
    sa.CheckConstraint('stake_cents >= 0', name='ck_bet_stake_nonneg'),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_bet_id'], ['bet.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', name='uq_bet_client_order_id'),
    sa.UniqueConstraint('kalshi_fill_id', name='uq_bet_kalshi_fill_id'),
    sa.UniqueConstraint('kalshi_order_id', name='uq_bet_kalshi_order_id')
    )
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.create_index('ix_bet_market', ['market_id'], unique=False)
        batch_op.create_index('ix_bet_placed_at', ['placed_at'], unique=False)
        batch_op.create_index('ix_bet_sport_status', ['sport', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_index('ix_bet_sport_status')
        batch_op.drop_index('ix_bet_placed_at')
        batch_op.drop_index('ix_bet_market')

    op.drop_table('bet')
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_index('ix_suggestion_sport_status')
        batch_op.drop_index('ix_suggestion_group')

    op.drop_table('suggestion')
    op.drop_table('position')
    op.drop_table('market')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index('ix_game_sport_status_kickoff')

    op.drop_table('game')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
